### ISSUE TITLE
Images are missing

### ISSUE THREAD

**Issue by ttodua** [HandBrake/HandBrake-docs#122] opened 2020-12-20 16:19 UTC
On some pages, images were missing. For example, here:
https://handbrake.fr/docs/en/1.3.0/technical/anamorphic-guide.html

**Comment by bradleysepos** [comment] 2021-01-10 23:38
Thanks, marking as duplicate of #46. These will be fixed as we re-write these articles, which were copied over from the old Trac Wiki (:gasp:).

**Closed by bradleysepos** 2021-01-10 23:38 UTC
Labels: Duplicate
