### ISSUE TITLE
Upscaling should be enabled for converting videos without 1:1 PAR

### ISSUE THREAD

**Issue by MisterAnderson91** [HandBrake/HandBrake-docs#89] opened 2019-11-14 21:42 UTC
At the moment, default behaviour is to block upscaling in the GUI. This makes enough sense for simple upscaling.

I argue this should be adjusted for non-square PAR videos such as DVD imports. I argue that a drop from 576 lines to 406 (a 30% reduction) is unacceptable. If the need to convert a non-square PAR video to a standard 1:1 resolution is needed due to video player incompatibilities, then upscaling just the horizontal resolution should be enabled to allow for the highest quality video output. 

I don't think the loss in quality is acceptable in these circumstances due to how high that loss is, for no reason other than a GUI tweak.

**Comment by sr55** [comment] 2019-11-14 21:46
Duplicate of https://github.com/HandBrake/HandBrake/issues/1633 

Also please note this is the HandBrake Documentation issue tracker. Not the HandBrake app issue tracker linked above.

**Closed by sr55** 2019-11-14 21:46 UTC

**Comment by MisterAnderson91** [comment] 2019-11-14 21:51
My bad, didn't notice I'd ended up in the handbrake-docs issue trackers, makes sense why I hadn't found the duplicate.
